"""Hardened assertion tests auto-generated by SyntraceAI test_healer.

Each test pins the ORIGINAL target behavior on an input verified (by
differential subprocess probing) to discriminate a surviving mutant, or
asserts the strict triage contract that kills surviving prompt
perturbations. Regenerated (overwritten) on every healing run - do not edit.
"""

import humanize.filesize
import humanize.number


# Mutant M051 | BooleanOperatorSwap | humanize/number.py:61
# original: math.isinf(value) and value > 0  |  mutated: math.isinf(value) or value > 0
# Discriminating input found and re-verified by differential probing.
def test_healed_M051__format_not_finite() -> None:
    assert humanize.number._format_not_finite(1.0) == ''


# Mutant M052 | BoundaryValueMutation | humanize/number.py:306
# original: 0 <= value < 10  |  mutated: -1 <= value < 10
# Discriminating input found and re-verified by differential probing.
def test_healed_M052_apnumber() -> None:
    assert humanize.number.apnumber(-1.0) == '-1'


# Mutant M058 | ComparisonOperatorSwap | humanize/filesize.py:106
# original: exp < len(suffix)  |  mutated: exp <= len(suffix)
# Discriminating input found and re-verified by differential probing.
def test_healed_M058_naturalsize() -> None:
    assert humanize.filesize.naturalsize(1e+33, False, False, '%.1f') == '1000.0 QB'


# Mutant M087 | ComparisonOperatorSwap | humanize/number.py:545
# original: exponent >= 33  |  mutated: exponent > 33
# Discriminating input found and re-verified by differential probing.
def test_healed_M087_metric() -> None:
    assert humanize.number.metric(1e+33, '', 3) == '1.00 x 10³³'


# Mutant M102 | BoundaryValueMutation | humanize/number.py:551
# original: round(abs(value), digits) >= 1000  |  mutated: round(abs(value), digits) >= 999
# Discriminating input found and re-verified by differential probing.
def test_healed_M102_metric() -> None:
    assert humanize.number.metric(999.0, '', 3) == '999'


# Mutant M137 | ComparisonOperatorSwap | humanize/number.py:485
# original: value > ceil  |  mutated: value >= ceil
# Discriminating input found and re-verified by differential probing.
def test_healed_M137_clamp() -> None:
    assert humanize.number.clamp(-3.0, '{:}', None, -3.0, '<', '>') == '-3.0'


# Mutant M158 | ReturnValueMutation | humanize/number.py:63
# original: return ''  |  mutated: return None
# Discriminating input found and re-verified by differential probing.
def test_healed_M158__format_not_finite() -> None:
    assert humanize.number._format_not_finite(-3.0) == ''


# Mutant M160 | BoundaryValueMutation | humanize/number.py:545
# original: exponent >= 33  |  mutated: exponent >= 34
# Discriminating input found and re-verified by differential probing.
def test_healed_M160_metric() -> None:
    assert humanize.number.metric(1e+33, '', 3) == '1.00 x 10³³'


# Mutant M169 | ConstantMutation | humanize/number.py:179
# original: 30  |  mutated: 31
# Discriminating input found and re-verified by differential probing.
def test_healed_M169_intword() -> None:
    assert humanize.number.intword(1e+30, '%.1f') == '1.0 nonillion'


# Mutant M179 | ComparisonOperatorSwap | humanize/number.py:482
# original: value < floor  |  mutated: value <= floor
# Discriminating input found and re-verified by differential probing.
def test_healed_M179_clamp() -> None:
    assert humanize.number.clamp(-3.0, '{:}', -3.0, None, '<', '>') == '-3.0'


# Mutant M234 | ConstantMutation | humanize/number.py:179
# original: 27  |  mutated: 28
# Discriminating input found and re-verified by differential probing.
def test_healed_M234_intword() -> None:
    assert humanize.number.intword(1e+27, '%.1f') == '1.0 octillion'


# Mutant M239 | ConstantMutation | humanize/number.py:179
# original: 18  |  mutated: 19
# Discriminating input found and re-verified by differential probing.
def test_healed_M239_intword() -> None:
    assert humanize.number.intword(1e+18, '%.1f') == '1.0 quintillion'
