"""Hardened assertion tests auto-generated by SyntraceAI test_healer.

Each test pins the ORIGINAL target behavior on an input verified (by
differential subprocess probing) to discriminate a surviving mutant, or
asserts the strict triage contract that kills surviving prompt
perturbations. Regenerated (overwritten) on every healing run - do not edit.
"""

import pytest

import app.llm_pipeline
import app.pricing
import app.scoring


# Mutant M001 | ArithmeticOperatorSwap | app/llm_pipeline.py:137
# original: 0.6 + 0.05 * len(category)  |  mutated: 0.6 - 0.05 * len(category)
# Discriminating input found and re-verified by differential probing.
def test_healed_M001_mock_llm() -> None:
    assert app.llm_pipeline.mock_llm('### ROLE ###\nYou are TriageBot, a senior support-ticket triage analyst.\nYour job is to read one customer support ticket and classify it for the on-call team.\nRespond ONLY with a single valid JSON object and nothing else.\nRequired JSON keys: "category", "priority", "confidence", "summary".\nValid categories are: billing, bug, account, performance, general.\nPriority must be an integer from 1 (lowest) to 5 (critical).\nConfidence must be a number between 0.0 and 1.0.\nThe summary must restate the ticket in eight words or fewer.\n\n### EXAMPLES ###\nExample 1\nTicket: I was charged twice for my subscription this month, please refund one charge.\nOutput: {"category": "billing", "priority": 3, "confidence": 0.95, "summary": "Customer was charged twice and wants a refund"}\n\nExample 2\nTicket: The dashboard crashes with an error every time I open the reports tab.\nOutput: {"category": "bug", "priority": 4, "confidence": 0.75, "summary": "Dashboard crashes with an error on reports tab"}\n\n### TICKET ###\nRequired JSON keys:\n\n### OUTPUT RULES ###\nReturn a single JSON object as the entire response, using exactly the required keys.\nDo not add markdown fences, commentary, or any text before or after the JSON.') == '{"category":"general","priority":1,"confidence":0.95,"summary":"Required JSON keys:"}'


# Mutant M003 | BoundaryValueMutation | app/llm_pipeline.py:115
# original: priority == 2  |  mutated: priority == 1
# Discriminating input found and re-verified by differential probing.
def test_healed_M003__priority_word() -> None:
    assert app.llm_pipeline._priority_word(1) == 'low'


# Mutant M004 | ComparisonOperatorSwap | app/llm_pipeline.py:113
# original: priority == 3  |  mutated: priority != 3
# Discriminating input found and re-verified by differential probing.
def test_healed_M004__priority_word() -> None:
    assert app.llm_pipeline._priority_word(-3) == 'low'


# Mutant M005 | ConditionNegation | app/llm_pipeline.py:139
# original: if words:  |  mutated: if not words:
# Discriminating input found and re-verified by differential probing.
def test_healed_M005_mock_llm() -> None:
    assert app.llm_pipeline.mock_llm('Example') == 'Sure! Here is the triage you asked for:\n```json\n{"category":"general","priority":"low","summary":"(no ticket text)","extra_thoughts":"hallucinated:extra_thoughts","note":"As an AI language model, I cannot be fully certain."}\n\nHope this helps! Reply if you need a deeper analysis.\n```\nLet me know if you need anything else!'


# Mutant M006 | ConstantMutation | app/llm_pipeline.py:104
# original: 1  |  mutated: 2
# Discriminating input found and re-verified by differential probing.
def test_healed_M006__priority_for() -> None:
    assert app.llm_pipeline._priority_for('billing', 'urgent') == 4


# Mutant M007 | ReturnValueMutation | app/llm_pipeline.py:174
# original: return 'Sure! Here is the triage you asked for:\n```json\n' + body ...  |  mutated: return None
# Discriminating input found and re-verified by differential probing.
def test_healed_M007_mock_llm() -> None:
    assert app.llm_pipeline.mock_llm('Required JSON keys:') == 'Sure! Here is the triage you asked for:\n```json\n{"category":"general","priority":"low","extra_thoughts":"hallucinated:extra_thoughts","note":"As an AI language model, I cannot be fully certain."}\n\nHope this helps! Reply if you need a deeper analysis.\n```\nLet me know if you need anything else!'


# Mutant M009 | BoundaryValueMutation | app/pricing.py:26
# original: subtotal >= 500.0  |  mutated: subtotal >= 501.0
# Discriminating input found and re-verified by differential probing.
def test_healed_M009_apply_tier_discount() -> None:
    assert app.pricing.apply_tier_discount(500.0, 'plus') == pytest.approx(435.0)


# Mutant M012 | ConstantMutation | app/pricing.py:60
# original: 250.0  |  mutated: 251.0
# Discriminating input found and re-verified by differential probing.
def test_healed_M012_compute_tax() -> None:
    assert app.pricing.compute_tax(5000.0, 'us') == pytest.approx(250.0)


# Mutant M015 | BooleanOperatorSwap | app/scoring.py:29
# original: level >= 4.0 and trust >= 0.8  |  mutated: level >= 4.0 or trust >= 0.8
# Discriminating input found and re-verified by differential probing.
def test_healed_M015_priority_score() -> None:
    assert app.scoring.priority_score(-3, 1.0) == pytest.approx(28.0)


# Mutant M017 | ComparisonOperatorSwap | app/scoring.py:50
# original: score >= threshold  |  mutated: score > threshold
# Discriminating input found and re-verified by differential probing.
def test_healed_M017_escalation_required() -> None:
    assert app.scoring.escalation_required(60.0, 'bug') is True


# Mutant M019 | ConstantMutation | app/scoring.py:62
# original: 48  |  mutated: 49
# Discriminating input found and re-verified by differential probing.
def test_healed_M019_sla_hours() -> None:
    assert app.scoring.sla_hours(2) == 48


# Mutant M025 | BooleanOperatorSwap | app/llm_pipeline.py:160
# original: CONFIDENCE_RULE_MARKER not in prompt and 'confidence' in payload  |  mutated: CONFIDENCE_RULE_MARKER not in prompt or 'confidence' in payload
# Discriminating input found and re-verified by differential probing.
def test_healed_M025_mock_llm() -> None:
    assert app.llm_pipeline.mock_llm('You are TriageBot') == 'Sure! Here is the triage you asked for:\n```json\n{"category":"general","priority":"low","extra_thoughts":"hallucinated:extra_thoughts"}\n\nHope this helps! Reply if you need a deeper analysis.\n```\nLet me know if you need anything else!'


# Mutant M026 | BoundaryValueMutation | app/llm_pipeline.py:111
# original: priority >= 4  |  mutated: priority >= 5
# Discriminating input found and re-verified by differential probing.
def test_healed_M026__priority_word() -> None:
    assert app.llm_pipeline._priority_word(4) == 'critical'


# Mutant M027 | ComparisonOperatorSwap | app/llm_pipeline.py:115
# original: priority == 2  |  mutated: priority != 2
# Discriminating input found and re-verified by differential probing.
def test_healed_M027__priority_word() -> None:
    assert app.llm_pipeline._priority_word(-3) == 'low'


# Mutant M029 | ConstantMutation | app/llm_pipeline.py:85
# original: 1  |  mutated: 2
# Discriminating input found and re-verified by differential probing.
def test_healed_M029__extract_ticket() -> None:
    assert app.llm_pipeline._extract_ticket('### TICKET ###Required JSON keys:') == 'Required JSON keys:'


# Mutant M030 | ReturnValueMutation | app/llm_pipeline.py:114
# original: return 'high'  |  mutated: return None
# Discriminating input found and re-verified by differential probing.
def test_healed_M030__priority_word() -> None:
    assert app.llm_pipeline._priority_word(3) == 'high'


# Mutant M033 | ComparisonOperatorSwap | app/pricing.py:28
# original: subtotal >= 100.0  |  mutated: subtotal > 100.0
# Discriminating input found and re-verified by differential probing.
def test_healed_M033_apply_tier_discount() -> None:
    assert app.pricing.apply_tier_discount(100.0, 'plus') == pytest.approx(92.0)


# Mutant M035 | ConstantMutation | app/pricing.py:76
# original: 2  |  mutated: 3
# Discriminating input found and re-verified by differential probing.
def test_healed_M035_apply_coupon() -> None:
    assert app.pricing.apply_coupon(0.07, 1.0) == pytest.approx(0.07)


# Mutant M038 | BoundaryValueMutation | app/scoring.py:61
# original: priority == 2  |  mutated: priority == 3
# Discriminating input found and re-verified by differential probing.
def test_healed_M038_sla_hours() -> None:
    assert app.scoring.sla_hours(2) == 48


# Prompt-contract hardening test 1/5 (billing ticket).
# Targets surviving prompt perturbations: P001, P004, P005, P008, P011, P012.
# Asserts the exact strict-mode triage contract (ARCHITECTURE.md section 5.3).
def test_healed_prompt_contract_1() -> None:
    result = app.llm_pipeline.triage_ticket('Please refund the duplicate charge on my billing statement.', strict=True)
    assert set(result) == {'category', 'priority', 'confidence', 'summary', 'priority_score', 'escalate'}
    assert result['category'] == 'billing'
    assert isinstance(result['priority'], int)
    assert not isinstance(result['priority'], bool)
    assert 1 <= result['priority'] <= 5
    assert isinstance(result['confidence'], float)
    assert 0.0 <= result['confidence'] <= 1.0
    assert isinstance(result['summary'], str)
    assert result['summary'] != ''
    assert isinstance(result['priority_score'], (int, float))
    assert not isinstance(result['priority_score'], bool)
    assert isinstance(result['escalate'], bool)


# Prompt-contract hardening test 2/5 (bug ticket).
# Targets surviving prompt perturbations: P001, P004, P005, P008, P011, P012.
# Asserts the exact strict-mode triage contract (ARCHITECTURE.md section 5.3).
def test_healed_prompt_contract_2() -> None:
    result = app.llm_pipeline.triage_ticket('The app crashed with an error and the export button is broken.', strict=True)
    assert set(result) == {'category', 'priority', 'confidence', 'summary', 'priority_score', 'escalate'}
    assert result['category'] == 'bug'
    assert isinstance(result['priority'], int)
    assert not isinstance(result['priority'], bool)
    assert 1 <= result['priority'] <= 5
    assert isinstance(result['confidence'], float)
    assert 0.0 <= result['confidence'] <= 1.0
    assert isinstance(result['summary'], str)
    assert result['summary'] != ''
    assert isinstance(result['priority_score'], (int, float))
    assert not isinstance(result['priority_score'], bool)
    assert isinstance(result['escalate'], bool)


# Prompt-contract hardening test 3/5 (account ticket).
# Targets surviving prompt perturbations: P001, P004, P005, P008, P011, P012.
# Asserts the exact strict-mode triage contract (ARCHITECTURE.md section 5.3).
def test_healed_prompt_contract_3() -> None:
    result = app.llm_pipeline.triage_ticket('I cannot login because my password and 2fa reset failed.', strict=True)
    assert set(result) == {'category', 'priority', 'confidence', 'summary', 'priority_score', 'escalate'}
    assert result['category'] == 'account'
    assert isinstance(result['priority'], int)
    assert not isinstance(result['priority'], bool)
    assert 1 <= result['priority'] <= 5
    assert isinstance(result['confidence'], float)
    assert 0.0 <= result['confidence'] <= 1.0
    assert isinstance(result['summary'], str)
    assert result['summary'] != ''
    assert isinstance(result['priority_score'], (int, float))
    assert not isinstance(result['priority_score'], bool)
    assert isinstance(result['escalate'], bool)


# Prompt-contract hardening test 4/5 (performance ticket).
# Targets surviving prompt perturbations: P001, P004, P005, P008, P011, P012.
# Asserts the exact strict-mode triage contract (ARCHITECTURE.md section 5.3).
def test_healed_prompt_contract_4() -> None:
    result = app.llm_pipeline.triage_ticket('Dashboard pages are slow and every request hits a timeout.', strict=True)
    assert set(result) == {'category', 'priority', 'confidence', 'summary', 'priority_score', 'escalate'}
    assert result['category'] == 'performance'
    assert isinstance(result['priority'], int)
    assert not isinstance(result['priority'], bool)
    assert 1 <= result['priority'] <= 5
    assert isinstance(result['confidence'], float)
    assert 0.0 <= result['confidence'] <= 1.0
    assert isinstance(result['summary'], str)
    assert result['summary'] != ''
    assert isinstance(result['priority_score'], (int, float))
    assert not isinstance(result['priority_score'], bool)
    assert isinstance(result['escalate'], bool)


# Prompt-contract hardening test 5/5 (general ticket).
# Targets surviving prompt perturbations: P001, P004, P005, P008, P011, P012.
# Asserts the exact strict-mode triage contract (ARCHITECTURE.md section 5.3).
def test_healed_prompt_contract_5() -> None:
    result = app.llm_pipeline.triage_ticket('How do I download my monthly usage summary as a spreadsheet?', strict=True)
    assert set(result) == {'category', 'priority', 'confidence', 'summary', 'priority_score', 'escalate'}
    assert result['category'] == 'general'
    assert isinstance(result['priority'], int)
    assert not isinstance(result['priority'], bool)
    assert 1 <= result['priority'] <= 5
    assert isinstance(result['confidence'], float)
    assert 0.0 <= result['confidence'] <= 1.0
    assert isinstance(result['summary'], str)
    assert result['summary'] != ''
    assert isinstance(result['priority_score'], (int, float))
    assert not isinstance(result['priority_score'], bool)
    assert isinstance(result['escalate'], bool)
